version: "3.9"

services:

  mysql:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: evolution

    volumes:
      - mysql_data:/var/lib/mysql

    deploy:
      placement:
        constraints:
          - node.role == manager

    networks:
      - traefik_public

volumes:
  mysql_data:

networks:
  traefik_public:
    external: true
