version: "3.9"

services:

  evolution:
    image: atendai/evolution-api:latest

    environment:
      SERVER_URL: "https://api.thiagocantalovo.com"

      AUTHENTICATION_API_KEY: ${EVOLUTION_API_KEY}

      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "mysql"

      DATABASE_CONNECTION_URI: "mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/evolution"

      REDIS_ENABLED: "true"
      REDIS_URI: "redis://redis:6379"

      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: "redis://redis:6379"

      SESSION_PHONE_CLIENT: "Evolution"

      CONFIG_SESSION_PHONE_VERSION: "2.3000.1023204200"

      PROTOCOL: "https"

      CORS_ORIGIN: "*"

    deploy:
      placement:
        constraints:
          - node.role == manager

      labels:
        - traefik.enable=true

        - traefik.http.routers.evolution.rule=Host(`api.thiagocantalovo.com`)
        - traefik.http.routers.evolution.entrypoints=websecure
        - traefik.http.routers.evolution.tls.certresolver=le
        - traefik.http.services.evolution.loadbalancer.server.port=8080

    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
