version: "3.9"

services:

  redis:
    image: redis:7-alpine

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    deploy:
      placement:
        constraints:
          - node.role == manager

    networks:
      - traefik_public

volumes:
  redis_data:

networks:
  traefik_public:
    external: true